package dev.jade.todolist.common.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Builder;
import lombok.Getter;

import java.time.Instant;
import java.util.Map;

/**
 * Unified error response structure for all API errors.
 * Provides consistent error information across all exception types.
 */
@Getter
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ErrorResponse {

    /**
     * Machine-readable error code (e.g., "SECTION_NOT_FOUND")
     */
    private final String errorCode;

    /**
     * User-facing error message (safe to display in UI)
     */
    private final String userMessage;

    /**
     * Developer-facing error message (detailed diagnostic information)
     */
    private final String developerMessage;

    /**
     * HTTP status code
     */
    private final int httpStatus;

    /**
     * Timestamp when error occurred (generated by database or system)
     */
    private final Instant timestamp;

    /**
     * Request path where error occurred
     */
    private final String path;

    /**
     * Optional correlation ID for request tracking
     */
    private final String correlationId;

    /**
     * Optional field-specific validation errors
     * Used for 400 BAD REQUEST validation failures
     */
    private final Map<String, String> fieldErrors;

    /**
     * Optional list version for snapshot pagination context
     */
    private final Instant listVersion;
}

/**
 * Builder for creating error responses with common patterns.
 */
@SuppressWarnings("unused")
class ErrorResponseBuilder {

    /**
     * Create a basic error response
     */
    public static ErrorResponse basic(
            String errorCode,
            String userMessage,
            String developerMessage,
            int httpStatus,
            String path
    ) {
        return ErrorResponse.builder()
                .errorCode(errorCode)
                .userMessage(userMessage)
                .developerMessage(developerMessage)
                .httpStatus(httpStatus)
                .timestamp(Instant.now())
                .path(path)
                .build();
    }

    /**
     * Create a validation error response with field errors
     */
    public static ErrorResponse validation(
            String userMessage,
            String developerMessage,
            Map<String, String> fieldErrors,
            String path
    ) {
        return ErrorResponse.builder()
                .errorCode("VALIDATION_ERROR")
                .userMessage(userMessage)
                .developerMessage(developerMessage)
                .httpStatus(400)
                .timestamp(Instant.now())
                .path(path)
                .fieldErrors(fieldErrors)
                .build();
    }

    /**
     * Create an error response with list version (for snapshot pagination)
     */
    public static ErrorResponse withListVersion(
            String errorCode,
            String userMessage,
            String developerMessage,
            int httpStatus,
            String path,
            Instant listVersion
    ) {
        return ErrorResponse.builder()
                .errorCode(errorCode)
                .userMessage(userMessage)
                .developerMessage(developerMessage)
                .httpStatus(httpStatus)
                .timestamp(Instant.now())
                .path(path)
                .listVersion(listVersion)
                .build();
    }
}