package dev.jade.todolist.section.dto.request;

import dev.jade.todolist.domain.enums.InsertPosition;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Getter;

@Getter
public class SectionRequest {

    @NotBlank(message = "Name is required")
    @Size(max = 50, message = "Name cannot exceed 50 characters")
    private String sectionName;

    /**
     * LexoRank for ordering (generated by frontend or left null for auto-generation)
     * If null, server will generate appropriate rank based on position
     */
    @Size(max = 50, message = "Rank cannot exceed 50 characters")
    private String rank;

    /**
     * Optional: Insert position hint ('top', 'bottom', or null for default)
     * Used when rank is null to determine where to insert
     */
    private InsertPosition insertPosition;
}